#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_TPPlayerBase

#include "Basic.hpp"

#include "ABP_TPPlayerBase_classes.hpp"
#include "ABP_TPPlayerBase_parameters.hpp"


namespace SDK
{

// Function ABP_TPPlayerBase.ABP_TPPlayerBase_C.ExecuteUbergraph_ABP_TPPlayerBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_TPPlayerBase_C::ExecuteUbergraph_ABP_TPPlayerBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_TPPlayerBase_C", "ExecuteUbergraph_ABP_TPPlayerBase");

	Params::ABP_TPPlayerBase_C_ExecuteUbergraph_ABP_TPPlayerBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_TPPlayerBase.ABP_TPPlayerBase_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_TPPlayerBase_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_TPPlayerBase_C", "AnimGraph");

	Params::ABP_TPPlayerBase_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_TPPlayerBase.ABP_TPPlayerBase_C.FullBodyAction
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       FullBodyAction_0                                       (Parm, OutParm, NoDestructor)

void UABP_TPPlayerBase_C::FullBodyAction(const struct FPoseLink& InPose, struct FPoseLink* FullBodyAction_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_TPPlayerBase_C", "FullBodyAction");

	Params::ABP_TPPlayerBase_C_FullBodyAction Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (FullBodyAction_0 != nullptr)
		*FullBodyAction_0 = std::move(Parms.FullBodyAction_0);
}

}

