#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioExtensions

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class AudioExtensions.SoundfieldEncodingSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEncodingSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEncodingSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEncodingSettingsBase")
	}
	static class USoundfieldEncodingSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEncodingSettingsBase>();
	}
};
DUMPER7_ASSERTS_USoundfieldEncodingSettingsBase;

// Class AudioExtensions.AudioEndpointSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UAudioEndpointSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioEndpointSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AudioEndpointSettingsBase")
	}
	static class UAudioEndpointSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioEndpointSettingsBase>();
	}
};
DUMPER7_ASSERTS_UAudioEndpointSettingsBase;

// Class AudioExtensions.DummyEndpointSettings
// 0x0000 (0x0030 - 0x0030)
class UDummyEndpointSettings final : public UAudioEndpointSettingsBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DummyEndpointSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DummyEndpointSettings")
	}
	static class UDummyEndpointSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDummyEndpointSettings>();
	}
};
DUMPER7_ASSERTS_UDummyEndpointSettings;

// Class AudioExtensions.SpatializationPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USpatializationPluginSourceSettingsBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SpatializationPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpatializationPluginSourceSettingsBase")
	}
	static class USpatializationPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatializationPluginSourceSettingsBase>();
	}
};
DUMPER7_ASSERTS_USpatializationPluginSourceSettingsBase;

// Class AudioExtensions.OcclusionPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UOcclusionPluginSourceSettingsBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OcclusionPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OcclusionPluginSourceSettingsBase")
	}
	static class UOcclusionPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOcclusionPluginSourceSettingsBase>();
	}
};
DUMPER7_ASSERTS_UOcclusionPluginSourceSettingsBase;

// Class AudioExtensions.ReverbPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UReverbPluginSourceSettingsBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ReverbPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReverbPluginSourceSettingsBase")
	}
	static class UReverbPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReverbPluginSourceSettingsBase>();
	}
};
DUMPER7_ASSERTS_UReverbPluginSourceSettingsBase;

// Class AudioExtensions.SoundModulatorBase
// 0x0000 (0x0030 - 0x0030)
class USoundModulatorBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundModulatorBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundModulatorBase")
	}
	static class USoundModulatorBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundModulatorBase>();
	}
};
DUMPER7_ASSERTS_USoundModulatorBase;

// Class AudioExtensions.SoundfieldEndpointSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEndpointSettingsBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEndpointSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEndpointSettingsBase")
	}
	static class USoundfieldEndpointSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEndpointSettingsBase>();
	}
};
DUMPER7_ASSERTS_USoundfieldEndpointSettingsBase;

// Class AudioExtensions.SoundfieldEffectSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEffectSettingsBase final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEffectSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEffectSettingsBase")
	}
	static class USoundfieldEffectSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEffectSettingsBase>();
	}
};
DUMPER7_ASSERTS_USoundfieldEffectSettingsBase;

// Class AudioExtensions.SoundfieldEffectBase
// 0x0008 (0x0038 - 0x0030)
class USoundfieldEffectBase final : public UObject
{
public:
	class USoundfieldEffectSettingsBase*          Settings;                                          // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEffectBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEffectBase")
	}
	static class USoundfieldEffectBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEffectBase>();
	}
};
DUMPER7_ASSERTS_USoundfieldEffectBase;

}

