#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseValuableBag

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BaseValuableBag.BP_BaseValuableBag_C
// 0x0020 (0x03C0 - 0x03A0)
class ABP_BaseValuableBag_C : public ASBZAttractableBagItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      FX_Leak;                                           // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        EndPlayNiagaraTransform;                           // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         End_Play_Niagara_System;                           // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BaseValuableBag(int32 EntryPoint);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void BP_OnZiplineAttachmentChanged(bool bIsAttached);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BaseValuableBag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BaseValuableBag_C")
	}
	static class ABP_BaseValuableBag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BaseValuableBag_C>();
	}
};
DUMPER7_ASSERTS_ABP_BaseValuableBag_C;

}

