#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackItemMethBagBurnt

#include "Basic.hpp"

#include "BP_BackItemBagBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BackItemMethBagBurnt.BP_BackItemMethBagBurnt_C
// 0x0008 (0x0320 - 0x0318)
class ABP_BackItemMethBagBurnt_C final : public ABP_BackItemBagBase_C
{
public:
	class UNiagaraComponent*                      FX_Bag_Dyed;                                       // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BackItemMethBagBurnt_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BackItemMethBagBurnt_C")
	}
	static class ABP_BackItemMethBagBurnt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BackItemMethBagBurnt_C>();
	}
};
DUMPER7_ASSERTS_ABP_BackItemMethBagBurnt_C;

}

