#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticCausticSoda

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CosmeticCausticSoda.BP_CosmeticCausticSoda_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_CosmeticCausticSoda_C final : public ASBZCosmeticProp
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CosmeticCausticSoda_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CosmeticCausticSoda_C")
	}
	static class ABP_CosmeticCausticSoda_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CosmeticCausticSoda_C>();
	}
};
DUMPER7_ASSERTS_ABP_CosmeticCausticSoda_C;

}

