#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarriedInteractableBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CarriedInteractableBase.BP_CarriedInteractableBase_C.ExecuteUbergraph_BP_CarriedInteractableBase
// 0x0020 (0x0020 - 0x0000)
struct BP_CarriedInteractableBase_C_ExecuteUbergraph_BP_CarriedInteractableBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZBaseInteractableComponent*          K2Node_ComponentBoundEvent_Interactable;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ComponentBoundEvent_Interactor;             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsLocallyControlledInteractor; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_CarriedInteractableBase_C_ExecuteUbergraph_BP_CarriedInteractableBase;

// Function BP_CarriedInteractableBase.BP_CarriedInteractableBase_C.BndEvt__BP_CarriedInteractableBase_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct BP_CarriedInteractableBase_C_BndEvt__BP_CarriedInteractableBase_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature final
{
public:
	class USBZBaseInteractableComponent*          Interactable_0;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsLocallyControlledInteractor;                    // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_CarriedInteractableBase_C_BndEvt__BP_CarriedInteractableBase_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature;

// Function BP_CarriedInteractableBase.BP_CarriedInteractableBase_C.GetSensorOutlineComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_CarriedInteractableBase_C_GetSensorOutlineComponent final
{
public:
	class USBZOutlineComponent*                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CarriedInteractableBase_C_GetSensorOutlineComponent;

// Function BP_CarriedInteractableBase.BP_CarriedInteractableBase_C.GetSensorComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_CarriedInteractableBase_C_GetSensorComponent final
{
public:
	class USBZSensorComponent*                    ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CarriedInteractableBase_C_GetSensorComponent;

}

