#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticBag

#include "Basic.hpp"

#include "BP_CosmeticBag_classes.hpp"
#include "BP_CosmeticBag_parameters.hpp"


namespace SDK
{

// Function BP_CosmeticBag.BP_CosmeticBag_C.ExecuteUbergraph_BP_CosmeticBag
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticBag_C::ExecuteUbergraph_BP_CosmeticBag(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "ExecuteUbergraph_BP_CosmeticBag");

	Params::BP_CosmeticBag_C_ExecuteUbergraph_BP_CosmeticBag Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.OnPooled
// (Event, Public, BlueprintEvent)

void ABP_CosmeticBag_C::OnPooled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "OnPooled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.OnUnpooled
// (Event, Public, BlueprintEvent)

void ABP_CosmeticBag_C::OnUnpooled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "OnUnpooled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticBag_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "ReceiveTick");

	Params::BP_CosmeticBag_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CosmeticBag_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.GetAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimSequence**                   Animation                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticBag_C::GetAnimation(float Duration, class UAnimSequence** Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "GetAnimation");

	Params::BP_CosmeticBag_C_GetAnimation Parms{};

	Parms.Duration = Duration;

	UObject::ProcessEvent(Func, &Parms);

	if (Animation != nullptr)
		*Animation = Parms.Animation;
}


// Function BP_CosmeticBag.BP_CosmeticBag_C.PlayAnimation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimSequence*                    Animation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticBag_C::PlayAnimation(class UAnimSequence* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticBag_C", "PlayAnimation");

	Params::BP_CosmeticBag_C_PlayAnimation Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}

}

