#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Chus_FlammableLiquid

#include "Basic.hpp"

#include "BP_Chus_FlammableLiquid_classes.hpp"
#include "BP_Chus_FlammableLiquid_parameters.hpp"


namespace SDK
{

// Function BP_Chus_FlammableLiquid.BP_Chus_FlammableLiquid_C.ExecuteUbergraph_BP_Chus_FlammableLiquid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Chus_FlammableLiquid_C::ExecuteUbergraph_BP_Chus_FlammableLiquid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chus_FlammableLiquid_C", "ExecuteUbergraph_BP_Chus_FlammableLiquid");

	Params::BP_Chus_FlammableLiquid_C_ExecuteUbergraph_BP_Chus_FlammableLiquid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chus_FlammableLiquid.BP_Chus_FlammableLiquid_C.BndEvt__BP_Chus_FlammableLiquid_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Chus_FlammableLiquid_C::BndEvt__BP_Chus_FlammableLiquid_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chus_FlammableLiquid_C", "BndEvt__BP_Chus_FlammableLiquid_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature");

	Params::BP_Chus_FlammableLiquid_C_BndEvt__BP_Chus_FlammableLiquid_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chus_FlammableLiquid.BP_Chus_FlammableLiquid_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Chus_FlammableLiquid_C::OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chus_FlammableLiquid_C", "OnStateChanged");

	Params::BP_Chus_FlammableLiquid_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo = bStateToChangeTo;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}

}

