#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DefeatFeedback

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DefeatFeedback.BP_DefeatFeedback_C
// 0x0000 (0x0308 - 0x0308)
class UBP_DefeatFeedback_C final : public USBZLocalPlayerFeedback
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DefeatFeedback_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DefeatFeedback_C")
	}
	static class UBP_DefeatFeedback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DefeatFeedback_C>();
	}
};
DUMPER7_ASSERTS_UBP_DefeatFeedback_C;

}

