#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ECMJammer

#include "Basic.hpp"

#include "BP_ECMJammer_classes.hpp"
#include "BP_ECMJammer_parameters.hpp"


namespace SDK
{

// Function BP_ECMJammer.BP_ECMJammer_C.ExecuteUbergraph_BP_ECMJammer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ECMJammer_C::ExecuteUbergraph_BP_ECMJammer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ECMJammer_C", "ExecuteUbergraph_BP_ECMJammer");

	Params::BP_ECMJammer_C_ExecuteUbergraph_BP_ECMJammer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ECMJammer.BP_ECMJammer_C.OnActivatedUsing
// (Event, Protected, BlueprintEvent)

void ABP_ECMJammer_C::OnActivatedUsing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ECMJammer_C", "OnActivatedUsing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ECMJammer.BP_ECMJammer_C.OnActivated
// (Event, Protected, BlueprintEvent)

void ABP_ECMJammer_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ECMJammer_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ECMJammer.BP_ECMJammer_C.OnJammerEffectEnded
// (Event, Protected, BlueprintEvent)

void ABP_ECMJammer_C::OnJammerEffectEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ECMJammer_C", "OnJammerEffectEnded");

	UObject::ProcessEvent(Func, nullptr);
}

}

