#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ECMJammer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AkAudio_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ECMJammer.BP_ECMJammer_C
// 0x0020 (0x05A0 - 0x0580)
class ABP_ECMJammer_C final : public ASBZECMJammer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0580(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Interactable_Collision;                            // 0x0588(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           Ak;                                                // 0x0590(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ECMJammer(int32 EntryPoint);
	void OnActivatedUsing();
	void OnActivated();
	void OnJammerEffectEnded();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ECMJammer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ECMJammer_C")
	}
	static class ABP_ECMJammer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ECMJammer_C>();
	}
};
DUMPER7_ASSERTS_ABP_ECMJammer_C;

}

