#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LA_Civ_Scripted_VIP_PoisonDrink

#include "Basic.hpp"

#include "BP_LA_Civ_Scripted_VIP_PoisonDrink_classes.hpp"
#include "BP_LA_Civ_Scripted_VIP_PoisonDrink_parameters.hpp"


namespace SDK
{

// Function BP_LA_Civ_Scripted_VIP_PoisonDrink.BP_LA_Civ_Scripted_VIP_PoisonDrink_C.ExecuteUbergraph_BP_LA_Civ_Scripted_VIP_PoisonDrink
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LA_Civ_Scripted_VIP_PoisonDrink_C::ExecuteUbergraph_BP_LA_Civ_Scripted_VIP_PoisonDrink(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LA_Civ_Scripted_VIP_PoisonDrink_C", "ExecuteUbergraph_BP_LA_Civ_Scripted_VIP_PoisonDrink");

	Params::BP_LA_Civ_Scripted_VIP_PoisonDrink_C_ExecuteUbergraph_BP_LA_Civ_Scripted_VIP_PoisonDrink Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LA_Civ_Scripted_VIP_PoisonDrink.BP_LA_Civ_Scripted_VIP_PoisonDrink_C.BndEvt__BP_LA_Civ_Scripted_VIP_PoisonDrink_SBZLifeAction_K2Node_ComponentBoundEvent_1_SBZLifeActionStopEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class ASBZCharacter*                    Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZLifeActionInstance*           ActionInstance                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZLifeActionSlot*               ActionSlot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZLifeActionStopReason                Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LA_Civ_Scripted_VIP_PoisonDrink_C::BndEvt__BP_LA_Civ_Scripted_VIP_PoisonDrink_SBZLifeAction_K2Node_ComponentBoundEvent_1_SBZLifeActionStopEventDelegate__DelegateSignature(class ASBZCharacter* Character, class USBZLifeActionInstance* ActionInstance, class USBZLifeActionSlot* ActionSlot, ESBZLifeActionStopReason Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LA_Civ_Scripted_VIP_PoisonDrink_C", "BndEvt__BP_LA_Civ_Scripted_VIP_PoisonDrink_SBZLifeAction_K2Node_ComponentBoundEvent_1_SBZLifeActionStopEventDelegate__DelegateSignature");

	Params::BP_LA_Civ_Scripted_VIP_PoisonDrink_C_BndEvt__BP_LA_Civ_Scripted_VIP_PoisonDrink_SBZLifeAction_K2Node_ComponentBoundEvent_1_SBZLifeActionStopEventDelegate__DelegateSignature Parms{};

	Parms.Character = Character;
	Parms.ActionInstance = ActionInstance;
	Parms.ActionSlot = ActionSlot;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}

}

