#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Level_DoctorBag

#include "Basic.hpp"

#include "BP_Placeable_DoctorBag_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Level_DoctorBag.BP_Level_DoctorBag_C
// 0x0000 (0x05D0 - 0x05D0)
class ABP_Level_DoctorBag_C final : public ABP_Placeable_DoctorBag_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Level_DoctorBag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Level_DoctorBag_C")
	}
	static class ABP_Level_DoctorBag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Level_DoctorBag_C>();
	}
};
DUMPER7_ASSERTS_ABP_Level_DoctorBag_C;

}

