#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MLChildSave

#include "Basic.hpp"

#include "UDS_ModSaveData_structs.hpp"
#include "BP_MLSaveGame_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MLChildSave.BP_MLChildSave_C
// 0x00C0 (0x0100 - 0x0040)
class UBP_MLChildSave_C final : public UBP_MLSaveGame_Base_C
{
public:
	class FString                                 SlotName;                                          // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMap<class UPDA_ModMeta_C*, struct FUDS_ModSaveData> UIModSaveData;                              // 0x0050(0x0050)(Edit, BlueprintVisible)
	TMap<class UPDA_ModMeta_C*, struct FUDS_ModSaveData> HiddenModSaveData;                          // 0x00A0(0x0050)(Edit, BlueprintVisible)
	class FString                                 MLVersion;                                         // 0x00F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, AdvancedDisplay, HasGetValueTypeHash)

public:
	void AddModSaveData(class UPDA_ModMeta_C* ModMetaData);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MLChildSave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MLChildSave_C")
	}
	static class UBP_MLChildSave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MLChildSave_C>();
	}
};
DUMPER7_ASSERTS_UBP_MLChildSave_C;

}

