#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Order_GoToLure

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Order_GoToLure.BP_Order_GoToLure_C
// 0x0000 (0x0230 - 0x0230)
class UBP_Order_GoToLure_C final : public USBZAIOrder_GoToLure
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Order_GoToLure_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Order_GoToLure_C")
	}
	static class UBP_Order_GoToLure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Order_GoToLure_C>();
	}
};
DUMPER7_ASSERTS_UBP_Order_GoToLure_C;

}

