#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PaintingBagSecured

#include "Basic.hpp"

#include "BP_BaseBagSecured_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PaintingBagSecured.BP_PaintingBagSecured_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_PaintingBagSecured_C final : public ABP_BaseBagSecured_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PaintingBagSecured_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PaintingBagSecured_C")
	}
	static class ABP_PaintingBagSecured_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PaintingBagSecured_C>();
	}
};
DUMPER7_ASSERTS_ABP_PaintingBagSecured_C;

}

