#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PropaneCanister_01_A

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AkAudio_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PropaneCanister_01_A.BP_PropaneCanister_01_A_C
// 0x0018 (0x04B8 - 0x04A0)
class ABP_PropaneCanister_01_A_C final : public ASBZExplosiveTrap
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Mesh;                                              // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsLongCanister_;                                  // 0x04B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();
	void BndEvt__BP_TestExplosiveFuelTank_NiagaraComponent_K2Node_ComponentBoundEvent_0_ActorComponentActivatedSignature__DelegateSignature(class UActorComponent* Component, bool bReset);
	void ExecuteUbergraph_BP_PropaneCanister_01_A(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PropaneCanister_01_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PropaneCanister_01_A_C")
	}
	static class ABP_PropaneCanister_01_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PropaneCanister_01_A_C>();
	}
};
DUMPER7_ASSERTS_ABP_PropaneCanister_01_A_C;

}

