#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SecurityCameraDestroyedFeedback

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SecurityCameraDestroyedFeedback.BP_SecurityCameraDestroyedFeedback_C
// 0x0000 (0x0308 - 0x0308)
class UBP_SecurityCameraDestroyedFeedback_C final : public USBZLocalPlayerFeedback
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SecurityCameraDestroyedFeedback_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SecurityCameraDestroyedFeedback_C")
	}
	static class UBP_SecurityCameraDestroyedFeedback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SecurityCameraDestroyedFeedback_C>();
	}
};
DUMPER7_ASSERTS_UBP_SecurityCameraDestroyedFeedback_C;

}

