#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmallDestruction_GlassBottle_01_C

#include "Basic.hpp"

#include "BP_SmallDestruction_GlassBottle_01_C_classes.hpp"
#include "BP_SmallDestruction_GlassBottle_01_C_parameters.hpp"


namespace SDK
{

// Function BP_SmallDestruction_GlassBottle_01_C.BP_SmallDestruction_GlassBottle_01_C_C.ExecuteUbergraph_BP_SmallDestruction_GlassBottle_01_C
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SmallDestruction_GlassBottle_01_C_C::ExecuteUbergraph_BP_SmallDestruction_GlassBottle_01_C(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallDestruction_GlassBottle_01_C_C", "ExecuteUbergraph_BP_SmallDestruction_GlassBottle_01_C");

	Params::BP_SmallDestruction_GlassBottle_01_C_C_ExecuteUbergraph_BP_SmallDestruction_GlassBottle_01_C Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SmallDestruction_GlassBottle_01_C.BP_SmallDestruction_GlassBottle_01_C_C.BndEvt__BP_SmallDestruction_GlassBottle_01_C_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// ESBZCosmeticDestructionType             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FSBZCosmeticDestructionContext&HitContext                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_SmallDestruction_GlassBottle_01_C_C::BndEvt__BP_SmallDestruction_GlassBottle_01_C_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SmallDestruction_GlassBottle_01_C_C", "BndEvt__BP_SmallDestruction_GlassBottle_01_C_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature");

	Params::BP_SmallDestruction_GlassBottle_01_C_C_BndEvt__BP_SmallDestruction_GlassBottle_01_C_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature Parms{};

	Parms.Type = Type;
	Parms.HitContext = std::move(HitContext);

	UObject::ProcessEvent(Func, &Parms);
}

}

