#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_VentilationRoof_02_Rotation

#include "Basic.hpp"

#include "bp_VentilationRoof_02_Rotation_classes.hpp"


namespace SDK
{

// Function bp_VentilationRoof_02_Rotation.bp_VentilationRoof_02_Rotation_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_VentilationRoof_02_Rotation_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("bp_VentilationRoof_02_Rotation_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

