#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_RoomSpawnInsideLoc

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_RoomSpawnInsideLoc.BPI_RoomSpawnInsideLoc_C.SpawnItemInContainer
// 0x0018 (0x0018 - 0x0000)
struct BPI_RoomSpawnInsideLoc_C_SpawnItemInContainer final
{
public:
	class UClass*                                 WhatShould_Spawn;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_RoomSpawnController_C*              RoomControllerRef;                                 // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 SpawnedActor;                                      // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_RoomSpawnInsideLoc_C_SpawnItemInContainer;

}

