#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_FloodLight

#include "Basic.hpp"

#include "BPL_FloodLight_classes.hpp"
#include "BPL_FloodLight_parameters.hpp"


namespace SDK
{

// Function BPL_FloodLight.BPL_FloodLight_C.ExecuteUbergraph_BPL_FloodLight
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPL_FloodLight_C::ExecuteUbergraph_BPL_FloodLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_FloodLight_C", "ExecuteUbergraph_BPL_FloodLight");

	Params::BPL_FloodLight_C_ExecuteUbergraph_BPL_FloodLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPL_FloodLight.BPL_FloodLight_C.BndEvt__BPL_FloodLight_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// ESBZCosmeticDestructionType             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FSBZCosmeticDestructionContext&HitContext                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABPL_FloodLight_C::BndEvt__BPL_FloodLight_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_FloodLight_C", "BndEvt__BPL_FloodLight_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature");

	Params::BPL_FloodLight_C_BndEvt__BPL_FloodLight_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature Parms{};

	Parms.Type = Type;
	Parms.HitContext = std::move(HitContext);

	UObject::ProcessEvent(Func, &Parms);
}

}

