#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_ArmoredTransport

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass C_ArmoredTransport.C_ArmoredTransport_C
// 0x0010 (0x0350 - 0x0340)
class AC_ArmoredTransport_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ALevelSequenceActor*                    C_RoadRage_Master_01_ExecuteUbergraph_C_ArmoredTransport_RefProperty; // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnIntroFinished();
	void IntroSequenceChanged(bool bIsStarted);
	void ExecuteUbergraph_C_ArmoredTransport(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_ArmoredTransport_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_ArmoredTransport_C")
	}
	static class AC_ArmoredTransport_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AC_ArmoredTransport_C>();
	}
};
DUMPER7_ASSERTS_AC_ArmoredTransport_C;

}

