#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_SWAT_Shotgun

#include "Basic.hpp"

#include "CH_BaseCommonSwat_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CH_SWAT_Shotgun.CH_SWAT_Shotgun_C
// 0x0000 (0x1D00 - 0x1D00)
class ACH_SWAT_Shotgun_C final : public ACH_BaseCommonSwat_C
{
public:
	class UStaticMeshComponent*                   Helmet;                                            // 0x1CF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CH_SWAT_Shotgun_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CH_SWAT_Shotgun_C")
	}
	static class ACH_SWAT_Shotgun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACH_SWAT_Shotgun_C>();
	}
};
DUMPER7_ASSERTS_ACH_SWAT_Shotgun_C;

}

