#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_FireWeapon_Pistol_SE5

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_FireWeapon_Pistol_SE5.CS_FireWeapon_Pistol_SE5_C
// 0x0000 (0x01B0 - 0x01B0)
class UCS_FireWeapon_Pistol_SE5_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CS_FireWeapon_Pistol_SE5_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CS_FireWeapon_Pistol_SE5_C")
	}
	static class UCS_FireWeapon_Pistol_SE5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_FireWeapon_Pistol_SE5_C>();
	}
};
DUMPER7_ASSERTS_UCS_FireWeapon_Pistol_SE5_C;

}

