#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataRegistry

#include "Basic.hpp"

#include "DataRegistry_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function DataRegistry.DataRegistrySubsystem.AcquireItemBP
// 0x0030 (0x0030 - 0x0000)
struct DataRegistrySubsystem_AcquireItemBP final
{
public:
	struct FDataRegistryId                        ItemId;                                            // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const struct FDataRegistryId& ItemId, const struct FDataRegistryLookup& ResolvedLookup, EDataRegistryAcquireStatus Status)> AcquireCallback; // 0x0018(0x0014)(Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x002C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_AcquireItemBP;

// Function DataRegistry.DataRegistrySubsystem.Conv_DataRegistryIdToString
// 0x0028 (0x0028 - 0x0000)
struct DataRegistrySubsystem_Conv_DataRegistryIdToString final
{
public:
	struct FDataRegistryId                        DataRegistryId;                                    // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataRegistrySubsystem_Conv_DataRegistryIdToString;

// Function DataRegistry.DataRegistrySubsystem.Conv_DataRegistryTypeToString
// 0x0020 (0x0020 - 0x0000)
struct DataRegistrySubsystem_Conv_DataRegistryTypeToString final
{
public:
	struct FDataRegistryType                      DataRegistryType;                                  // 0x0000(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataRegistrySubsystem_Conv_DataRegistryTypeToString;

// Function DataRegistry.DataRegistrySubsystem.EqualEqual_DataRegistryId
// 0x0034 (0x0034 - 0x0000)
struct DataRegistrySubsystem_EqualEqual_DataRegistryId final
{
public:
	struct FDataRegistryId                        A;                                                 // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDataRegistryId                        B;                                                 // 0x0018(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_EqualEqual_DataRegistryId;

// Function DataRegistry.DataRegistrySubsystem.EqualEqual_DataRegistryType
// 0x001C (0x001C - 0x0000)
struct DataRegistrySubsystem_EqualEqual_DataRegistryType final
{
public:
	struct FDataRegistryType                      A;                                                 // 0x0000(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDataRegistryType                      B;                                                 // 0x000C(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_EqualEqual_DataRegistryType;

// Function DataRegistry.DataRegistrySubsystem.EvaluateDataRegistryCurve
// 0x0028 (0x0028 - 0x0000)
struct DataRegistrySubsystem_EvaluateDataRegistryCurve final
{
public:
	struct FDataRegistryId                        ItemId;                                            // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InputValue;                                        // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DefaultValue;                                      // 0x001C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EDataRegistrySubsystemGetItemResult           OutResult;                                         // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         OutValue;                                          // 0x0024(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataRegistrySubsystem_EvaluateDataRegistryCurve;

// Function DataRegistry.DataRegistrySubsystem.FindCachedItemBP
// 0x0028 (0x0028 - 0x0000)
struct DataRegistrySubsystem_FindCachedItemBP final
{
public:
	struct FDataRegistryId                        ItemId;                                            // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EDataRegistrySubsystemGetItemResult           OutResult;                                         // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTableRowBase                          OutItem;                                           // 0x0020(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataRegistrySubsystem_FindCachedItemBP;

// Function DataRegistry.DataRegistrySubsystem.GetCachedItemBP
// 0x0028 (0x0028 - 0x0000)
struct DataRegistrySubsystem_GetCachedItemBP final
{
public:
	struct FDataRegistryId                        ItemId;                                            // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTableRowBase                          OutItem;                                           // 0x0018(0x0008)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_GetCachedItemBP;

// Function DataRegistry.DataRegistrySubsystem.GetCachedItemFromLookupBP
// 0x0048 (0x0048 - 0x0000)
struct DataRegistrySubsystem_GetCachedItemFromLookupBP final
{
public:
	struct FDataRegistryId                        ItemId;                                            // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDataRegistryLookup                    ResolvedLookup;                                    // 0x0018(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTableRowBase                          OutItem;                                           // 0x0038(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_GetCachedItemFromLookupBP;

// Function DataRegistry.DataRegistrySubsystem.IsValidDataRegistryId
// 0x001C (0x001C - 0x0000)
struct DataRegistrySubsystem_IsValidDataRegistryId final
{
public:
	struct FDataRegistryId                        DataRegistryId;                                    // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_IsValidDataRegistryId;

// Function DataRegistry.DataRegistrySubsystem.IsValidDataRegistryType
// 0x0010 (0x0010 - 0x0000)
struct DataRegistrySubsystem_IsValidDataRegistryType final
{
public:
	struct FDataRegistryType                      DataRegistryType;                                  // 0x0000(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_IsValidDataRegistryType;

// Function DataRegistry.DataRegistrySubsystem.NotEqual_DataRegistryId
// 0x0034 (0x0034 - 0x0000)
struct DataRegistrySubsystem_NotEqual_DataRegistryId final
{
public:
	struct FDataRegistryId                        A;                                                 // 0x0000(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDataRegistryId                        B;                                                 // 0x0018(0x0018)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_NotEqual_DataRegistryId;

// Function DataRegistry.DataRegistrySubsystem.NotEqual_DataRegistryType
// 0x001C (0x001C - 0x0000)
struct DataRegistrySubsystem_NotEqual_DataRegistryType final
{
public:
	struct FDataRegistryType                      A;                                                 // 0x0000(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDataRegistryType                      B;                                                 // 0x000C(0x000C)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DataRegistrySubsystem_NotEqual_DataRegistryType;

}

