#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_ArmoredTransport_Ext_VehiclePark_Prop

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass E_ArmoredTransport_Ext_VehiclePark_Prop.E_ArmoredTransport_Ext_VehiclePark_Prop_C
// 0x0000 (0x0340 - 0x0340)
class AE_ArmoredTransport_Ext_VehiclePark_Prop_C final : public ASBZLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("E_ArmoredTransport_Ext_VehiclePark_Prop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"E_ArmoredTransport_Ext_VehiclePark_Prop_C")
	}
	static class AE_ArmoredTransport_Ext_VehiclePark_Prop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AE_ArmoredTransport_Ext_VehiclePark_Prop_C>();
	}
};
DUMPER7_ASSERTS_AE_ArmoredTransport_Ext_VehiclePark_Prop_C;

}

