#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_PlaceECMJammer

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_PlaceECMJammer.GA_PlaceECMJammer_C
// 0x0000 (0x0560 - 0x0560)
class UGA_PlaceECMJammer_C final : public USBZPlaceECMJammerAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_PlaceECMJammer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_PlaceECMJammer_C")
	}
	static class UGA_PlaceECMJammer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_PlaceECMJammer_C>();
	}
};
DUMPER7_ASSERTS_UGA_PlaceECMJammer_C;

}

