#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Target

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Target.GA_Target_C
// 0x0000 (0x04D8 - 0x04D8)
class UGA_Target_C final : public USBZGameplayAbility_CharacterTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Target_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Target_C")
	}
	static class UGA_Target_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Target_C>();
	}
};
DUMPER7_ASSERTS_UGA_Target_C;

}

