#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SentryGun_Explosion

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SentryGun_Explosion.GE_SentryGun_Explosion_C
// 0x0000 (0x08C0 - 0x08C0)
class UGE_SentryGun_Explosion_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_SentryGun_Explosion_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_SentryGun_Explosion_C")
	}
	static class UGE_SentryGun_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SentryGun_Explosion_C>();
	}
};
DUMPER7_ASSERTS_UGE_SentryGun_Explosion_C;

}

