#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: struct_PlayerStatsToCompare

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct struct_PlayerStatsToCompare.struct_PlayerStatsToCompare
// 0x0034 (0x0034 - 0x0000)
struct Fstruct_PlayerStatsToCompare final
{
public:
	int32                                         CashSecured_2_C826E5204C9F603506B549BA3647D769;    // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LooseCashSecured_13_38ACF1924CCB8BDD3D565A9D3CF032BB; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalKIlls_14_85770DEB4D26D48611C0449887B09DB3;    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SpecialsKilled_15_54866AE24A85CAE6D72A0DB73290349C; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DamageDealt_16_F0C4C6694BD49F884403F291666E2C5B;   // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         HostagesTraded_17_8A9AA8EF4C40C3F3E73500A95E6C644A; // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PrimaryAccuracy_18_922996C848682805A6FF73AC3AA106DB; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SecondaryAccuracy_19_AD2A7E4D415F39BCAB3ED6AC2B2E87B5; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Headshots_29_ADFAD6024E40883306E07CAF61DAF95F;     // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Revives_27_E6D7245B4970C49561D372AD43B86DD2;       // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalDowns_21_1323B24B4F65872FEBBCA58B94BF9B7B;    // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DevicesHacked_22_F4F2342A4AF2D60ED9BD0997AF494E41; // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LocksPicked_24_248F0BD34AE0F77F3B779DA9A538E9E9;   // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Fstruct_PlayerStatsToCompare;

}

