#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UTD_Crew_FollowWard

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UTD_Crew_FollowWard.UTD_Crew_FollowWard_C
// 0x0000 (0x00B0 - 0x00B0)
class UUTD_Crew_FollowWard_C final : public USBZAIUtilityDecider
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UTD_Crew_FollowWard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UTD_Crew_FollowWard_C")
	}
	static class UUTD_Crew_FollowWard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUTD_Crew_FollowWard_C>();
	}
};
DUMPER7_ASSERTS_UUTD_Crew_FollowWard_C;

}

