#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SM_APT_SecurityCompanyDisplay

#include "Basic.hpp"

#include "WBP_SM_APT_SecurityCompanyDisplay_classes.hpp"
#include "WBP_SM_APT_SecurityCompanyDisplay_parameters.hpp"


namespace SDK
{

// Function WBP_SM_APT_SecurityCompanyDisplay.WBP_SM_APT_SecurityCompanyDisplay_C.ExecuteUbergraph_WBP_SM_APT_SecurityCompanyDisplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SM_APT_SecurityCompanyDisplay_C::ExecuteUbergraph_WBP_SM_APT_SecurityCompanyDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SM_APT_SecurityCompanyDisplay_C", "ExecuteUbergraph_WBP_SM_APT_SecurityCompanyDisplay");

	Params::WBP_SM_APT_SecurityCompanyDisplay_C_ExecuteUbergraph_WBP_SM_APT_SecurityCompanyDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SM_APT_SecurityCompanyDisplay.WBP_SM_APT_SecurityCompanyDisplay_C.OnSecurityCompanyAssetLoaded
// (Event, Public, BlueprintEvent)

void UWBP_SM_APT_SecurityCompanyDisplay_C::OnSecurityCompanyAssetLoaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SM_APT_SecurityCompanyDisplay_C", "OnSecurityCompanyAssetLoaded");

	UObject::ProcessEvent(Func, nullptr);
}

}

