#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_MainMenu_CrimeNet_ServerButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UI_MainMenu_CrimeNet_ServerButton.WBP_UI_MainMenu_CrimeNet_ServerButton_C
// 0x0228 (0x0598 - 0x0370)
class UWBP_UI_MainMenu_CrimeNet_ServerButton_C final : public USBZMenuButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Background;                                  // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Highlight;                                   // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_LevelName;                                    // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_Ping;                                         // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_PlayerCount;                                  // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_ServerData;                                   // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_ServerFull;                                   // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_UnableToJoin;                                 // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSBZOnlineSearchResult                 SBZSessionSearchResult;                            // 0x03B8(0x01E0)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_WBP_UI_MainMenu_CrimeNet_ServerButton(int32 EntryPoint);
	void ButtonSelected();
	void ButtonHoveredChanged(bool bInIsHovered);
	void ButtonFocusedChanged(bool bInHasFocus);
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void SetSessionInfo(const struct FSBZOnlineSearchResult& SBZOnlineSearchResult);
	class FText GetPartyTypeFromSessionParams(const struct FSBZOnlineSessionParams& SessionParams);
	void GetSessionInfo(struct FSBZOnlineSearchResult* SessionInfo);
	void IsJoinBlocked(bool* bIsJoinBlocked);
	void SetIsActive(bool bIsActive);
	void OnHover(bool bIsHovered);
	void OnFocus(bool bIsFocused);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_MainMenu_CrimeNet_ServerButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_MainMenu_CrimeNet_ServerButton_C")
	}
	static class UWBP_UI_MainMenu_CrimeNet_ServerButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_MainMenu_CrimeNet_ServerButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UI_MainMenu_CrimeNet_ServerButton_C;

}

