#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Social_ContextButton

#include "Basic.hpp"

#include "WBP_UI_Social_ContextButton_classes.hpp"
#include "WBP_UI_Social_ContextButton_parameters.hpp"


namespace SDK
{

// Function WBP_UI_Social_ContextButton.WBP_UI_Social_ContextButton_C.ExecuteUbergraph_WBP_UI_Social_ContextButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Social_ContextButton_C::ExecuteUbergraph_WBP_UI_Social_ContextButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Social_ContextButton_C", "ExecuteUbergraph_WBP_UI_Social_ContextButton");

	Params::WBP_UI_Social_ContextButton_C_ExecuteUbergraph_WBP_UI_Social_ContextButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Social_ContextButton.WBP_UI_Social_ContextButton_C.ButtonFocusedChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInHasFocus                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Social_ContextButton_C::ButtonFocusedChanged(bool bInHasFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Social_ContextButton_C", "ButtonFocusedChanged");

	Params::WBP_UI_Social_ContextButton_C_ButtonFocusedChanged Parms{};

	Parms.bInHasFocus = bInHasFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Social_ContextButton.WBP_UI_Social_ContextButton_C.ButtonSelected
// (Event, Protected, BlueprintEvent)

void UWBP_UI_Social_ContextButton_C::ButtonSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Social_ContextButton_C", "ButtonSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Social_ContextButton.WBP_UI_Social_ContextButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Social_ContextButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Social_ContextButton_C", "PreConstruct");

	Params::WBP_UI_Social_ContextButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Social_ContextButton.WBP_UI_Social_ContextButton_C.OnGainFocus
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isFocused                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Social_ContextButton_C::OnGainFocus(bool isFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Social_ContextButton_C", "OnGainFocus");

	Params::WBP_UI_Social_ContextButton_C_OnGainFocus Parms{};

	Parms.isFocused = isFocused;

	UObject::ProcessEvent(Func, &Parms);
}

}

