#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_SM_Replay

#include "Basic.hpp"

#include "WBP_UI_SM_Replay_classes.hpp"
#include "WBP_UI_SM_Replay_parameters.hpp"


namespace SDK
{

// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.ExecuteUbergraph_WBP_UI_SM_Replay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_SM_Replay_C::ExecuteUbergraph_WBP_UI_SM_Replay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "ExecuteUbergraph_WBP_UI_SM_Replay");

	Params::WBP_UI_SM_Replay_C_ExecuteUbergraph_WBP_UI_SM_Replay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.OnReplayStart
// (Event, Public, BlueprintEvent)

void UWBP_UI_SM_Replay_C::OnReplayStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "OnReplayStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__StopButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__StopButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__StopButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__PauseButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__PauseButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__PauseButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__ScrubForwardButton_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__ScrubForwardButton_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__ScrubForwardButton_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__ScrubBackwardButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__ScrubBackwardButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__ScrubBackwardButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__PlayPauseButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__PlayPauseButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__PlayPauseButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__ViewButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__ViewButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__ViewButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__PlayerButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__PlayerButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__PlayerButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__QuitButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__QuitButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__QuitButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__TimeDownButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__TimeDownButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__TimeDownButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.BndEvt__TimeUpButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_SM_Replay_C::BndEvt__TimeUpButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "BndEvt__TimeUpButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.OnReplayUpdate
// (Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    ReplayLength                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    ReplayElapased                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// float                                   ReplayElapsedPercent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_SM_Replay_C::OnReplayUpdate(const class FString& ReplayLength, const class FString& ReplayElapased, float ReplayElapsedPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "OnReplayUpdate");

	Params::WBP_UI_SM_Replay_C_OnReplayUpdate Parms{};

	Parms.ReplayLength = std::move(ReplayLength);
	Parms.ReplayElapased = std::move(ReplayElapased);
	Parms.ReplayElapsedPercent = ReplayElapsedPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.Get_ReplayProgressBar_Percent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_UI_SM_Replay_C::Get_ReplayProgressBar_Percent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "Get_ReplayProgressBar_Percent_0");

	Params::WBP_UI_SM_Replay_C_Get_ReplayProgressBar_Percent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UI_SM_Replay.WBP_UI_SM_Replay_C.Get_TimeDilation_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_UI_SM_Replay_C::Get_TimeDilation_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_Replay_C", "Get_TimeDilation_Text_0");

	Params::WBP_UI_SM_Replay_C_Get_TimeDilation_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

