#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_ThrowableStatus

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_Widget_ThrowableStatus.WBP_UI_Widget_ThrowableStatus_C.ExecuteUbergraph_WBP_UI_Widget_ThrowableStatus
// 0x0130 (0x0130 - 0x0000)
struct WBP_UI_Widget_ThrowableStatus_C_ExecuteUbergraph_WBP_UI_Widget_ThrowableStatus final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Play2DSound_ReturnValue;                  // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0018(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0040(0x0028)()
	int32                                         K2Node_Event_InAmmoInventory;                      // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0070(0x0018)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_2;                    // 0x0088(0x0028)()
	TSoftObjectPtr<class UPaperSprite>            K2Node_Event_InIcon;                               // 0x00B0(0x0030)(ConstParm, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E2[0x6];                                       // 0x00E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                Temp_object_Variable;                              // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPaperSprite*                           K2Node_DynamicCast_AsPaper_Sprite;                 // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ISlateTextureAtlasInterface> CallFunc_SetBrushFromAtlasInterface_AtlasRegion_CastInput; // 0x0108(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0118(0x0014)(ZeroConstructor, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_Widget_ThrowableStatus_C_ExecuteUbergraph_WBP_UI_Widget_ThrowableStatus;

// Function WBP_UI_Widget_ThrowableStatus.WBP_UI_Widget_ThrowableStatus_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_ThrowableStatus_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_Widget_ThrowableStatus_C_PreConstruct;

// Function WBP_UI_Widget_ThrowableStatus.WBP_UI_Widget_ThrowableStatus_C.OnAmmoInventoryChanged
// 0x0004 (0x0004 - 0x0000)
struct WBP_UI_Widget_ThrowableStatus_C_OnAmmoInventoryChanged final
{
public:
	int32                                         InAmmoInventory;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_ThrowableStatus_C_OnAmmoInventoryChanged;

// Function WBP_UI_Widget_ThrowableStatus.WBP_UI_Widget_ThrowableStatus_C.OnIconChanged
// 0x0030 (0x0030 - 0x0000)
struct WBP_UI_Widget_ThrowableStatus_C_OnIconChanged final
{
public:
	TSoftObjectPtr<class UPaperSprite>            InIcon;                                            // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_ThrowableStatus_C_OnIconChanged;

// Function WBP_UI_Widget_ThrowableStatus.WBP_UI_Widget_ThrowableStatus_C.OnLoaded_518521A6441661765F2132899331E941
// 0x0008 (0x0008 - 0x0000)
struct WBP_UI_Widget_ThrowableStatus_C_OnLoaded_518521A6441661765F2132899331E941 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_ThrowableStatus_C_OnLoaded_518521A6441661765F2132899331E941;

}

