#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Overskill_Container

#include "Basic.hpp"

#include "WBP_UI_Overskill_Container_classes.hpp"
#include "WBP_UI_Overskill_Container_parameters.hpp"


namespace SDK
{

// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.ExecuteUbergraph_WBP_UI_Overskill_Container
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::ExecuteUbergraph_WBP_UI_Overskill_Container(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "ExecuteUbergraph_WBP_UI_Overskill_Container");

	Params::WBP_UI_Overskill_Container_C_ExecuteUbergraph_WBP_UI_Overskill_Container Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.BndEvt__WBP_UI_Overskill_Container_OverskillSwitch_ControllerPrompt_K2Node_ComponentBoundEvent_9_SBZOnActionChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_UI_Overskill_Container_C::BndEvt__WBP_UI_Overskill_Container_OverskillSwitch_ControllerPrompt_K2Node_ComponentBoundEvent_9_SBZOnActionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "BndEvt__WBP_UI_Overskill_Container_OverskillSwitch_ControllerPrompt_K2Node_ComponentBoundEvent_9_SBZOnActionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.BndEvt__WBP_UI_Overskill_Container_Overkill_Switch_K2Node_ComponentBoundEvent_8_OnMenuButtonSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZMenuButton*                   Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::BndEvt__WBP_UI_Overskill_Container_Overkill_Switch_K2Node_ComponentBoundEvent_8_OnMenuButtonSelected__DelegateSignature(class USBZMenuButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "BndEvt__WBP_UI_Overskill_Container_Overkill_Switch_K2Node_ComponentBoundEvent_8_OnMenuButtonSelected__DelegateSignature");

	Params::WBP_UI_Overskill_Container_C_BndEvt__WBP_UI_Overskill_Container_Overkill_Switch_K2Node_ComponentBoundEvent_8_OnMenuButtonSelected__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.BndEvt__WBP_UI_Overskill_Container_WBP_MenuButton_K2Node_ComponentBoundEvent_7_OnMenuButtonStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZMenuButton*                   Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsEnabled_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Overskill_Container_C::BndEvt__WBP_UI_Overskill_Container_WBP_MenuButton_K2Node_ComponentBoundEvent_7_OnMenuButtonStateChanged__DelegateSignature(class USBZMenuButton* Button, bool bIsEnabled_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "BndEvt__WBP_UI_Overskill_Container_WBP_MenuButton_K2Node_ComponentBoundEvent_7_OnMenuButtonStateChanged__DelegateSignature");

	Params::WBP_UI_Overskill_Container_C_BndEvt__WBP_UI_Overskill_Container_WBP_MenuButton_K2Node_ComponentBoundEvent_7_OnMenuButtonStateChanged__DelegateSignature Parms{};

	Parms.Button = Button;
	Parms.bIsEnabled_0 = bIsEnabled_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.BndEvt__WBP_UI_Overskill_Container_WBP_Overskill_NavBar_K2Node_ComponentBoundEvent_0_OnIndexChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   NewIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::BndEvt__WBP_UI_Overskill_Container_WBP_Overskill_NavBar_K2Node_ComponentBoundEvent_0_OnIndexChanged__DelegateSignature(int32 NewIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "BndEvt__WBP_UI_Overskill_Container_WBP_Overskill_NavBar_K2Node_ComponentBoundEvent_0_OnIndexChanged__DelegateSignature");

	Params::WBP_UI_Overskill_Container_C_BndEvt__WBP_UI_Overskill_Container_WBP_Overskill_NavBar_K2Node_ComponentBoundEvent_0_OnIndexChanged__DelegateSignature Parms{};

	Parms.NewIndex = NewIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Overskill_Container_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.OnOverskillChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class USBZOverskillData*          InOverskillData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InProgress                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::OnOverskillChanged(const class USBZOverskillData* InOverskillData, float InProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "OnOverskillChanged");

	Params::WBP_UI_Overskill_Container_C_OnOverskillChanged Parms{};

	Parms.InOverskillData = InOverskillData;
	Parms.InProgress = InProgress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.UpdateLevelDetails
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::UpdateLevelDetails(int32 NewIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "UpdateLevelDetails");

	Params::WBP_UI_Overskill_Container_C_UpdateLevelDetails Parms{};

	Parms.NewIndex = NewIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.SetBaseInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Progress_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::SetBaseInfo(float Progress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "SetBaseInfo");

	Params::WBP_UI_Overskill_Container_C_SetBaseInfo Parms{};

	Parms.Progress_0 = Progress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.SetProgressBarDetails
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_UI_Overskill_Container_C::SetProgressBarDetails()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "SetProgressBarDetails");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.GetSkillDataByIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZSkillData**                   SkillData                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::GetSkillDataByIndex(int32 Index_0, class USBZSkillData** SkillData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "GetSkillDataByIndex");

	Params::WBP_UI_Overskill_Container_C_GetSkillDataByIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (SkillData != nullptr)
		*SkillData = Parms.SkillData;
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.GetCurrentLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Progress_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  CurrentLevel                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::GetCurrentLevel(float Progress_0, int32* CurrentLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "GetCurrentLevel");

	Params::WBP_UI_Overskill_Container_C_GetCurrentLevel Parms{};

	Parms.Progress_0 = Progress_0;

	UObject::ProcessEvent(Func, &Parms);

	if (CurrentLevel != nullptr)
		*CurrentLevel = Parms.CurrentLevel;
}


// Function WBP_UI_Overskill_Container.WBP_UI_Overskill_Container_C.GetProgressBarValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   InProgress                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  OutProgress                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Overskill_Container_C::GetProgressBarValue(float InProgress, float* OutProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Overskill_Container_C", "GetProgressBarValue");

	Params::WBP_UI_Overskill_Container_C_GetProgressBarValue Parms{};

	Parms.InProgress = InProgress;

	UObject::ProcessEvent(Func, &Parms);

	if (OutProgress != nullptr)
		*OutProgress = Parms.OutProgress;
}

}

