#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextEntry_Button

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TextEntry_Button.WBP_TextEntry_Button_C
// 0x0058 (0x03F0 - 0x0398)
class UWBP_TextEntry_Button_C final : public USBZTextEntryButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0398(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_TextBorder;                                 // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BorderEdge_I;                                      // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Background;                                  // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Editing;                                     // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Hover;                                       // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsEditingText;                                     // 0x03C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C9[0x7];                                      // 0x03C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Text_Hint_Override;                                // 0x03D0(0x0018)(Edit, BlueprintVisible)
	bool                                          IsPasswordOverride;                                // 0x03E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_TextEntry_Button(int32 EntryPoint);
	void EditingText(bool bInIsEditingText);
	void ButtonHoveredChanged(bool bInIsHovered);
	void ButtonFocusedChanged(bool bInHasFocus);
	void ButtonDisabledChanged(bool bInIsDisabled);
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void RefreshVisuals();
	void OnHoverVisuals(bool bIsHovered);
	void OnFocusedVisuals(bool bIsFocused);
	void OnDisabledVisuals(bool bIsDisabled_0);
	void ToggleEditingText();
	void ClearText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TextEntry_Button_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TextEntry_Button_C")
	}
	static class UWBP_TextEntry_Button_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TextEntry_Button_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TextEntry_Button_C;

}

