#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_HUD_AbilityActionInput

#include "Basic.hpp"

#include "WBP_UI_HUD_AbilityActionInput_classes.hpp"
#include "WBP_UI_HUD_AbilityActionInput_parameters.hpp"


namespace SDK
{

// Function WBP_UI_HUD_AbilityActionInput.WBP_UI_HUD_AbilityActionInput_C.ExecuteUbergraph_WBP_UI_HUD_AbilityActionInput
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_HUD_AbilityActionInput_C::ExecuteUbergraph_WBP_UI_HUD_AbilityActionInput(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_HUD_AbilityActionInput_C", "ExecuteUbergraph_WBP_UI_HUD_AbilityActionInput");

	Params::WBP_UI_HUD_AbilityActionInput_C_ExecuteUbergraph_WBP_UI_HUD_AbilityActionInput Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_HUD_AbilityActionInput.WBP_UI_HUD_AbilityActionInput_C.OnAbilityRemoved
// (BlueprintEvent)

void UWBP_UI_HUD_AbilityActionInput_C::OnAbilityRemoved()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_HUD_AbilityActionInput_C", "OnAbilityRemoved");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_HUD_AbilityActionInput.WBP_UI_HUD_AbilityActionInput_C.OnAbilityGiven
// (BlueprintEvent)

void UWBP_UI_HUD_AbilityActionInput_C::OnAbilityGiven()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_HUD_AbilityActionInput_C", "OnAbilityGiven");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_HUD_AbilityActionInput.WBP_UI_HUD_AbilityActionInput_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_HUD_AbilityActionInput_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_HUD_AbilityActionInput_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_HUD_AbilityActionInput.WBP_UI_HUD_AbilityActionInput_C.OnActivateAbilityStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInCanActivate                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_HUD_AbilityActionInput_C::OnActivateAbilityStateChanged(bool bInCanActivate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_HUD_AbilityActionInput_C", "OnActivateAbilityStateChanged");

	Params::WBP_UI_HUD_AbilityActionInput_C_OnActivateAbilityStateChanged Parms{};

	Parms.bInCanActivate = bInCanActivate;

	UObject::ProcessEvent(Func, &Parms);
}

}

