#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_Ping_RinoHud

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UI_Widget_Ping_RinoHud.WBP_UI_Widget_Ping_RinoHud_C
// 0x0040 (0x02F8 - 0x02B8)
class UWBP_UI_Widget_Ping_RinoHud_C final : public USBZPingWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_QualityColor;                               // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_PingValue;                                    // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           HighPingQualityColor;                              // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CriticalPingQualityColor;                          // 0x02E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAlwaysShowPing;                                   // 0x02F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_UI_Widget_Ping_RinoHud(int32 EntryPoint);
	void OnPingValueChanged(const int32 PingValue);
	void OnPingQualityChanged(const EPingQuality PingQuality);
	void PreConstruct(bool IsDesignTime);
	void UpdateValueText(int32 InPing);
	void UpdateQualityIcon(EPingQuality InPingQuality);
	void SetCorrectOpacity(bool Show);
	void ForceValueUpdate();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_Widget_Ping_RinoHud_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_Widget_Ping_RinoHud_C")
	}
	static class UWBP_UI_Widget_Ping_RinoHud_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_Ping_RinoHud_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UI_Widget_Ping_RinoHud_C;

}

