#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_ActionInput

#include "Basic.hpp"

#include "WBP_UI_Widget_ActionInput_classes.hpp"
#include "WBP_UI_Widget_ActionInput_parameters.hpp"


namespace SDK
{

// Function WBP_UI_Widget_ActionInput.WBP_UI_Widget_ActionInput_C.ExecuteUbergraph_WBP_UI_Widget_ActionInput
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Widget_ActionInput_C::ExecuteUbergraph_WBP_UI_Widget_ActionInput(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_ActionInput_C", "ExecuteUbergraph_WBP_UI_Widget_ActionInput");

	Params::WBP_UI_Widget_ActionInput_C_ExecuteUbergraph_WBP_UI_Widget_ActionInput Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_ActionInput.WBP_UI_Widget_ActionInput_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Widget_ActionInput_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_ActionInput_C", "PreConstruct");

	Params::WBP_UI_Widget_ActionInput_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

