#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PartyMember_ToolStatus

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_PartyMember_ToolStatus.WBP_PartyMember_ToolStatus_C.ExecuteUbergraph_WBP_PartyMember_ToolStatus
// 0x0138 (0x0138 - 0x0000)
struct WBP_PartyMember_ToolStatus_C_ExecuteUbergraph_WBP_PartyMember_ToolStatus final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_InAmmoInventory;                      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ISlateTextureAtlasInterface> CallFunc_SetBrushFromAtlasInterface_AtlasRegion_CastInput; // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0018(0x0018)()
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UPaperSprite>            K2Node_Event_InIcon;                               // 0x0038(0x0030)(ConstParm, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0070(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0098(0x0028)()
	class UObject*                                Temp_object_Variable;                              // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPaperSprite*                           K2Node_DynamicCast_AsPaper_Sprite;                 // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ISlateTextureAtlasInterface> CallFunc_SetBrushFromAtlasInterface_AtlasRegion_CastInput_1; // 0x00D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SelectFloat_ReturnValue;                  // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_2;                    // 0x00F8(0x0028)()
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0120(0x0014)(ZeroConstructor, NoDestructor)
};
DUMPER7_ASSERTS_WBP_PartyMember_ToolStatus_C_ExecuteUbergraph_WBP_PartyMember_ToolStatus;

// Function WBP_PartyMember_ToolStatus.WBP_PartyMember_ToolStatus_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_PartyMember_ToolStatus_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_PartyMember_ToolStatus_C_PreConstruct;

// Function WBP_PartyMember_ToolStatus.WBP_PartyMember_ToolStatus_C.OnIconChanged
// 0x0030 (0x0030 - 0x0000)
struct WBP_PartyMember_ToolStatus_C_OnIconChanged final
{
public:
	TSoftObjectPtr<class UPaperSprite>            InIcon;                                            // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PartyMember_ToolStatus_C_OnIconChanged;

// Function WBP_PartyMember_ToolStatus.WBP_PartyMember_ToolStatus_C.OnAmmoInventoryChanged
// 0x0004 (0x0004 - 0x0000)
struct WBP_PartyMember_ToolStatus_C_OnAmmoInventoryChanged final
{
public:
	int32                                         InAmmoInventory;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PartyMember_ToolStatus_C_OnAmmoInventoryChanged;

// Function WBP_PartyMember_ToolStatus.WBP_PartyMember_ToolStatus_C.OnLoaded_BA373E794BE56F89437E66AA1890CF13
// 0x0008 (0x0008 - 0x0000)
struct WBP_PartyMember_ToolStatus_C_OnLoaded_BA373E794BE56F89437E66AA1890CF13 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PartyMember_ToolStatus_C_OnLoaded_BA373E794BE56F89437E66AA1890CF13;

}

