#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_WeaponPartProgressionButton

#include "Basic.hpp"

#include "WBP_UI_WeaponPartProgressionButton_classes.hpp"
#include "WBP_UI_WeaponPartProgressionButton_parameters.hpp"


namespace SDK
{

// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.ExecuteUbergraph_WBP_UI_WeaponPartProgressionButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_WeaponPartProgressionButton_C::ExecuteUbergraph_WBP_UI_WeaponPartProgressionButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "ExecuteUbergraph_WBP_UI_WeaponPartProgressionButton");

	Params::WBP_UI_WeaponPartProgressionButton_C_ExecuteUbergraph_WBP_UI_WeaponPartProgressionButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "PreConstruct");

	Params::WBP_UI_WeaponPartProgressionButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.DisabledButtonSelected
// (Event, Protected, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::DisabledButtonSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "DisabledButtonSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.ButtonDisabledChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsDisabled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::ButtonDisabledChanged(bool bInIsDisabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "ButtonDisabledChanged");

	Params::WBP_UI_WeaponPartProgressionButton_C_ButtonDisabledChanged Parms{};

	Parms.bInIsDisabled = bInIsDisabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.DefaultButtonSet
// (Event, Protected, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::DefaultButtonSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "DefaultButtonSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.OnEquippedChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsEquipped                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::OnEquippedChanged(bool bInIsEquipped)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "OnEquippedChanged");

	Params::WBP_UI_WeaponPartProgressionButton_C_OnEquippedChanged Parms{};

	Parms.bInIsEquipped = bInIsEquipped;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.WeaponPartProgressionInitialized
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FSBZWeaponPartProgressionCurrent&InWeaponPartProgression                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_UI_WeaponPartProgressionButton_C::WeaponPartProgressionInitialized(const struct FSBZWeaponPartProgressionCurrent& InWeaponPartProgression)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "WeaponPartProgressionInitialized");

	Params::WBP_UI_WeaponPartProgressionButton_C_WeaponPartProgressionInitialized Parms{};

	Parms.InWeaponPartProgression = std::move(InWeaponPartProgression);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.ButtonFocusedChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInHasFocus                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::ButtonFocusedChanged(bool bInHasFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "ButtonFocusedChanged");

	Params::WBP_UI_WeaponPartProgressionButton_C_ButtonFocusedChanged Parms{};

	Parms.bInHasFocus = bInHasFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.OnFocusChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsFocused                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::OnFocusChanged(bool bIsFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "OnFocusChanged");

	Params::WBP_UI_WeaponPartProgressionButton_C_OnFocusChanged Parms{};

	Parms.bIsFocused = bIsFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.InitItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryBaseData*            InItemData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_WeaponPartProgressionButton_C::InitItem(class USBZInventoryBaseData* InItemData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "InitItem");

	Params::WBP_UI_WeaponPartProgressionButton_C_InitItem Parms{};

	Parms.InItemData = InItemData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.InitButtonState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZWeaponPartProgressionCurrent&InWeaponPartProgression                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_UI_WeaponPartProgressionButton_C::InitButtonState(const struct FSBZWeaponPartProgressionCurrent& InWeaponPartProgression)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "InitButtonState");

	Params::WBP_UI_WeaponPartProgressionButton_C_InitButtonState Parms{};

	Parms.InWeaponPartProgression = std::move(InWeaponPartProgression);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetDefaultButton
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetDefaultButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetDefaultButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.OnDisabledChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InDisabled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_WeaponPartProgressionButton_C::OnDisabledChanged(bool InDisabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "OnDisabledChanged");

	Params::WBP_UI_WeaponPartProgressionButton_C_OnDisabledChanged Parms{};

	Parms.InDisabled = InDisabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetLockedByDLC
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetLockedByDLC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetLockedByDLC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetCurrencyTypeAndValue
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int64                                   InCurrencyValue                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZCurrencyCode                        InCurrencyType                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_WeaponPartProgressionButton_C::SetCurrencyTypeAndValue(int64 InCurrencyValue, ESBZCurrencyCode InCurrencyType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetCurrencyTypeAndValue");

	Params::WBP_UI_WeaponPartProgressionButton_C_SetCurrencyTypeAndValue Parms{};

	Parms.InCurrencyValue = InCurrencyValue;
	Parms.InCurrencyType = InCurrencyType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetLockedByLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InLockedLevel                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_WeaponPartProgressionButton_C::SetLockedByLevel(int32 InLockedLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetLockedByLevel");

	Params::WBP_UI_WeaponPartProgressionButton_C_SetLockedByLevel Parms{};

	Parms.InLockedLevel = InLockedLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetDisabled
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetDisabledFocused
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetDisabledFocused()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetDisabledFocused");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetFocused
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetFocused()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetFocused");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_WeaponPartProgressionButton.WBP_UI_WeaponPartProgressionButton_C.SetDefault
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UI_WeaponPartProgressionButton_C::SetDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_WeaponPartProgressionButton_C", "SetDefault");

	UObject::ProcessEvent(Func, nullptr);
}

}

