#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PocketDrillWidget

#include "Basic.hpp"

#include "WBP_PocketDrillWidget_classes.hpp"
#include "WBP_PocketDrillWidget_parameters.hpp"


namespace SDK
{

// Function WBP_PocketDrillWidget.WBP_PocketDrillWidget_C.ExecuteUbergraph_WBP_PocketDrillWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PocketDrillWidget_C::ExecuteUbergraph_WBP_PocketDrillWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PocketDrillWidget_C", "ExecuteUbergraph_WBP_PocketDrillWidget");

	Params::WBP_PocketDrillWidget_C_ExecuteUbergraph_WBP_PocketDrillWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PocketDrillWidget.WBP_PocketDrillWidget_C.OnUpdateBreachState
// (Event, Public, BlueprintEvent)
// Parameters:
// ESBZBreachingEquipmentState             NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PocketDrillWidget_C::OnUpdateBreachState(ESBZBreachingEquipmentState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PocketDrillWidget_C", "OnUpdateBreachState");

	Params::WBP_PocketDrillWidget_C_OnUpdateBreachState Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}

}

