#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Settings_MultipleChoiceButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Settings_MultipleChoiceButton.WBP_Settings_MultipleChoiceButton_C
// 0x0040 (0x0460 - 0x0420)
class UWBP_Settings_MultipleChoiceButton_C final : public USBZSettingsButtonMultipleChoice
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0420(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Border_Image;                                      // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MouseOnly_TextButton_C*            Button_Left;                                       // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MouseOnly_TextButton_C*            Button_Right;                                      // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Background;                                  // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BG;                                          // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_OptionChoice;                                 // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_SettingName;                                  // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Settings_MultipleChoiceButton(int32 EntryPoint);
	void SettingChanged();
	void OptionNamesChanged();
	void SelectionNameChanged();
	void BndEvt__WBP_Settings_TwoChoiceButton_Button_Option1_K2Node_ComponentBoundEvent_2_OnMenuMouseButtonSelected__DelegateSignature(class USBZMenuMouseButton* Button);
	void BndEvt__WBP_Settings_TwoChoiceButton_Button_Option1_K2Node_ComponentBoundEvent_1_OnMenuMouseButtonSelected__DelegateSignature(class USBZMenuMouseButton* Button);
	void ButtonHoveredChanged(bool bInIsHovered);
	void ButtonFocusedChanged(bool bInHasFocus);
	void ButtonDisabledChanged(bool bInIsDisabled);
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void RefreshVisuals();
	void OnHoverVisuals(bool bIsHovered);
	void OnFocusedVisuals(bool bIsFocused);
	void OnDisabledVisuals(bool bIsDisabled_0);
	void ChoiceIndexVisuals(int32 ChoiceIndex_0);
	void InitializeVisuals();
	void UpdateSettingNameText();
	void UpdateOptionsText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Settings_MultipleChoiceButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Settings_MultipleChoiceButton_C")
	}
	static class UWBP_Settings_MultipleChoiceButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Settings_MultipleChoiceButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Settings_MultipleChoiceButton_C;

}

