#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_PlayerCarryStatusItem

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UI_Widget_PlayerCarryStatusItem.WBP_UI_Widget_PlayerCarryStatusItem_C
// 0x0018 (0x02A8 - 0x0290)
class UWBP_UI_Widget_PlayerCarryStatusItem_C final : public UUserWidget
{
public:
	class UWidgetAnimation*                       OnRemoved;                                         // 0x0290(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       OnAdded;                                           // 0x0298(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_BagIcon;                                     // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnChanged(class USBZCarryType* Type, bool IsAdded);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_Widget_PlayerCarryStatusItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_Widget_PlayerCarryStatusItem_C")
	}
	static class UWBP_UI_Widget_PlayerCarryStatusItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_PlayerCarryStatusItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UI_Widget_PlayerCarryStatusItem_C;

}

