#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_CrimeNet_TextButton

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.ExecuteUbergraph_WBP_UI_CrimeNet_TextButton
// 0x0020 (0x0020 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_ExecuteUbergraph_WBP_UI_CrimeNet_TextButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bInHasFocus;                          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ISlateTextureAtlasInterface> CallFunc_SetBrushFromAtlasInterface_AtlasRegion_CastInput; // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_ExecuteUbergraph_WBP_UI_CrimeNet_TextButton;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_PreConstruct;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.ButtonFocusedChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_ButtonFocusedChanged final
{
public:
	bool                                          bInHasFocus;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_ButtonFocusedChanged;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.OnFocusedVisuals
// 0x0118 (0x0118 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_OnFocusedVisuals final
{
public:
	bool                                          bIsFocused;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_1; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0020(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0048(0x0028)()
	bool                                          Temp_bool_Variable_2;                              // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_2;                    // 0x0078(0x0028)()
	struct FSlateColor                            K2Node_Select_Default_1;                           // 0x00A0(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_3;                    // 0x00C8(0x0028)()
	struct FSlateColor                            K2Node_Select_Default_2;                           // 0x00F0(0x0028)()
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_OnFocusedVisuals;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.OnDisabledVisuals
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_OnDisabledVisuals final
{
public:
	bool                                          bIsDisabled_0;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_OnDisabledVisuals;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.RefreshVisual
// 0x0002 (0x0002 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_RefreshVisual final
{
public:
	bool                                          CallFunc_IsHovered_ReturnValue;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue;             // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_RefreshVisual;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.SetButtonText
// 0x0018 (0x0018 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_SetButtonText final
{
public:
	class FText                                   InButtonText;                                      // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_SetButtonText;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.GetText
// 0x0030 (0x0030 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_GetText final
{
public:
	class FText                                   OutText;                                           // 0x0000(0x0018)(Parm, OutParm)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0018(0x0018)()
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_GetText;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.SetTextDescription
// 0x0018 (0x0018 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_SetTextDescription final
{
public:
	class FText                                   InDescription;                                     // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_SetTextDescription;

// Function WBP_UI_CrimeNet_TextButton.WBP_UI_CrimeNet_TextButton_C.OnHoverVisuals
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_CrimeNet_TextButton_C_OnHoverVisuals final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_CrimeNet_TextButton_C_OnHoverVisuals;

}

