#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_CategorySelectionScreen

#include "Basic.hpp"

#include "WBP_MainMenu_CategorySelectionScreen_classes.hpp"
#include "WBP_MainMenu_CategorySelectionScreen_parameters.hpp"


namespace SDK
{

// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.ExecuteUbergraph_WBP_MainMenu_CategorySelectionScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_CategorySelectionScreen_C::ExecuteUbergraph_WBP_MainMenu_CategorySelectionScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "ExecuteUbergraph_WBP_MainMenu_CategorySelectionScreen");

	Params::WBP_MainMenu_CategorySelectionScreen_C_ExecuteUbergraph_WBP_MainMenu_CategorySelectionScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenu_CategorySelectionScreen_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "PreConstruct");

	Params::WBP_MainMenu_CategorySelectionScreen_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.BndEvt__WBP_MainMenu_CategorySelectionScreen_WBP_DailyChallengesContainer_K2Node_ComponentBoundEvent_2_RerollUsed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenu_CategorySelectionScreen_C::BndEvt__WBP_MainMenu_CategorySelectionScreen_WBP_DailyChallengesContainer_K2Node_ComponentBoundEvent_2_RerollUsed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "BndEvt__WBP_MainMenu_CategorySelectionScreen_WBP_DailyChallengesContainer_K2Node_ComponentBoundEvent_2_RerollUsed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.OnLostStackFocused
// (Event, Protected, BlueprintEvent)

void UWBP_MainMenu_CategorySelectionScreen_C::OnLostStackFocused()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "OnLostStackFocused");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.OnGainedStackFocused
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      PreviousValue                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_CategorySelectionScreen_C::OnGainedStackFocused(const class FName& PreviousValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "OnGainedStackFocused");

	Params::WBP_MainMenu_CategorySelectionScreen_C_OnGainedStackFocused Parms{};

	Parms.PreviousValue = PreviousValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.OnControlsReferencePressed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_CategorySelectionScreen_C::OnControlsReferencePressed(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "OnControlsReferencePressed");

	Params::WBP_MainMenu_CategorySelectionScreen_C_OnControlsReferencePressed Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.OnAddedToStack
// (Event, Protected, BlueprintEvent)

void UWBP_MainMenu_CategorySelectionScreen_C::OnAddedToStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "OnAddedToStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_CategorySelectionScreen.WBP_MainMenu_CategorySelectionScreen_C.SetControlReference
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_CategorySelectionScreen_C::SetControlReference()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_CategorySelectionScreen_C", "SetControlReference");

	UObject::ProcessEvent(Func, nullptr);
}

}

