#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComputerUnlocked

#include "Basic.hpp"

#include "WBP_ComputerUnlocked_classes.hpp"
#include "WBP_ComputerUnlocked_parameters.hpp"


namespace SDK
{

// Function WBP_ComputerUnlocked.WBP_ComputerUnlocked_C.OnRep_CodePacket
// (BlueprintCallable, BlueprintEvent)

void UWBP_ComputerUnlocked_C::OnRep_CodePacket()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComputerUnlocked_C", "OnRep_CodePacket");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComputerUnlocked.WBP_ComputerUnlocked_C.UpdateDisplayText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZHackableDisplayText&   NewDisplayText                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ComputerUnlocked_C::UpdateDisplayText(const struct FSBZHackableDisplayText& NewDisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComputerUnlocked_C", "UpdateDisplayText");

	Params::WBP_ComputerUnlocked_C_UpdateDisplayText Parms{};

	Parms.NewDisplayText = std::move(NewDisplayText);

	UObject::ProcessEvent(Func, &Parms);
}

}

