#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_MainMenu_Blackbackground

#include "Basic.hpp"

#include "WBP_UI_MainMenu_Blackbackground_classes.hpp"
#include "WBP_UI_MainMenu_Blackbackground_parameters.hpp"


namespace SDK
{

// Function WBP_UI_MainMenu_Blackbackground.WBP_UI_MainMenu_Blackbackground_C.ExecuteUbergraph_WBP_UI_MainMenu_Blackbackground
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_MainMenu_Blackbackground_C::ExecuteUbergraph_WBP_UI_MainMenu_Blackbackground(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_MainMenu_Blackbackground_C", "ExecuteUbergraph_WBP_UI_MainMenu_Blackbackground");

	Params::WBP_UI_MainMenu_Blackbackground_C_ExecuteUbergraph_WBP_UI_MainMenu_Blackbackground Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_MainMenu_Blackbackground.WBP_UI_MainMenu_Blackbackground_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_MainMenu_Blackbackground_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_MainMenu_Blackbackground_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

