#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Inventory_HorizontalModGrid

#include "Basic.hpp"

#include "WBP_UI_Inventory_HorizontalModGrid_classes.hpp"
#include "WBP_UI_Inventory_HorizontalModGrid_parameters.hpp"


namespace SDK
{

// Function WBP_UI_Inventory_HorizontalModGrid.WBP_UI_Inventory_HorizontalModGrid_C.ExecuteUbergraph_WBP_UI_Inventory_HorizontalModGrid
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_HorizontalModGrid_C::ExecuteUbergraph_WBP_UI_Inventory_HorizontalModGrid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_HorizontalModGrid_C", "ExecuteUbergraph_WBP_UI_Inventory_HorizontalModGrid");

	Params::WBP_UI_Inventory_HorizontalModGrid_C_ExecuteUbergraph_WBP_UI_Inventory_HorizontalModGrid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_HorizontalModGrid.WBP_UI_Inventory_HorizontalModGrid_C.DisplayGrid
// (Event, Protected, BlueprintEvent)

void UWBP_UI_Inventory_HorizontalModGrid_C::DisplayGrid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_HorizontalModGrid_C", "DisplayGrid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Inventory_HorizontalModGrid.WBP_UI_Inventory_HorizontalModGrid_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Inventory_HorizontalModGrid_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_HorizontalModGrid_C", "PreConstruct");

	Params::WBP_UI_Inventory_HorizontalModGrid_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_HorizontalModGrid.WBP_UI_Inventory_HorizontalModGrid_C.CreateNewMod
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_UI_Inventory_ModGridIcon_C** OutWidget                                              (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_HorizontalModGrid_C::CreateNewMod(class UWBP_UI_Inventory_ModGridIcon_C** OutWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_HorizontalModGrid_C", "CreateNewMod");

	Params::WBP_UI_Inventory_HorizontalModGrid_C_CreateNewMod Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutWidget != nullptr)
		*OutWidget = Parms.OutWidget;
}

}

