#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_HUD_FPSCounter

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_HUD_FPSCounter.WBP_UI_HUD_FPSCounter_C.ExecuteUbergraph_WBP_UI_HUD_FPSCounter
// 0x000C (0x000C - 0x0000)
struct WBP_UI_HUD_FPSCounter_C_ExecuteUbergraph_WBP_UI_HUD_FPSCounter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bInIsDisplaying;                      // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_HUD_FPSCounter_C_ExecuteUbergraph_WBP_UI_HUD_FPSCounter;

// Function WBP_UI_HUD_FPSCounter.WBP_UI_HUD_FPSCounter_C.OnDisplayedChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_HUD_FPSCounter_C_OnDisplayedChanged final
{
public:
	bool                                          bInIsDisplaying;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_HUD_FPSCounter_C_OnDisplayedChanged;

}

