#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MouseOnly_TextButton

#include "Basic.hpp"

#include "WBP_MouseOnly_TextButton_classes.hpp"
#include "WBP_MouseOnly_TextButton_parameters.hpp"


namespace SDK
{

// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.ExecuteUbergraph_WBP_MouseOnly_TextButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MouseOnly_TextButton_C::ExecuteUbergraph_WBP_MouseOnly_TextButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "ExecuteUbergraph_WBP_MouseOnly_TextButton");

	Params::WBP_MouseOnly_TextButton_C_ExecuteUbergraph_WBP_MouseOnly_TextButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MouseOnly_TextButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.ButtonHoveredChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsHovered                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MouseOnly_TextButton_C::ButtonHoveredChanged(bool bInIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "ButtonHoveredChanged");

	Params::WBP_MouseOnly_TextButton_C_ButtonHoveredChanged Parms{};

	Parms.bInIsHovered = bInIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MouseOnly_TextButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "PreConstruct");

	Params::WBP_MouseOnly_TextButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_MouseOnly_TextButton_C::SetText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "SetText");

	Params::WBP_MouseOnly_TextButton_C_SetText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.SetFont
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSlateFontInfo&            InFont                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_MouseOnly_TextButton_C::SetFont(const struct FSlateFontInfo& InFont)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "SetFont");

	Params::WBP_MouseOnly_TextButton_C_SetFont Parms{};

	Parms.InFont = std::move(InFont);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.TextValue
// (Public, BlueprintCallable, BlueprintEvent, BlueprintPure)

void UWBP_MouseOnly_TextButton_C::TextValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "TextValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MouseOnly_TextButton.WBP_MouseOnly_TextButton_C.SetColours
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              InFontColor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              InBackgroundColor                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MouseOnly_TextButton_C::SetColours(const struct FLinearColor& InFontColor, const struct FLinearColor& InBackgroundColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MouseOnly_TextButton_C", "SetColours");

	Params::WBP_MouseOnly_TextButton_C_SetColours Parms{};

	Parms.InFontColor = std::move(InFontColor);
	Parms.InBackgroundColor = std::move(InBackgroundColor);

	UObject::ProcessEvent(Func, &Parms);
}

}

