#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_EscapeCounter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.ExecuteUbergraph_WBP_UI_Widget_EscapeCounter
// 0x0060 (0x0060 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_ExecuteUbergraph_WBP_UI_Widget_EscapeCounter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_Event_PlayersInVolumeOnLeft;                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_TotalPlayers_2;                       // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_PlayersInVolumeOnEntered;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_TotalPlayers_1;                       // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_PlayersInVolumeOnChanged;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_TotalPlayers;                         // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue_1;       // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_NewTime;                              // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0048(0x0018)()
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_ExecuteUbergraph_WBP_UI_Widget_EscapeCounter;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.OnEscapeTimerChanged
// 0x0004 (0x0004 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_OnEscapeTimerChanged final
{
public:
	int32                                         NewTime;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_OnEscapeTimerChanged;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.OnPlayerCountChanged
// 0x0008 (0x0008 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_OnPlayerCountChanged final
{
public:
	int32                                         PlayersInVolumeOnChanged;                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalPlayers;                                      // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_OnPlayerCountChanged;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.OnPlayersEnteredVolume
// 0x0008 (0x0008 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_OnPlayersEnteredVolume final
{
public:
	int32                                         PlayersInVolumeOnEntered;                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalPlayers;                                      // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_OnPlayersEnteredVolume;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.OnAllPlayersLeftVolume
// 0x0008 (0x0008 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_OnAllPlayersLeftVolume final
{
public:
	int32                                         PlayersInVolumeOnLeft;                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalPlayers;                                      // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_OnAllPlayersLeftVolume;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_PreConstruct;

// Function WBP_UI_Widget_EscapeCounter.WBP_UI_Widget_EscapeCounter_C.UpdateEscapeWidgetText
// 0x00B0 (0x00B0 - 0x0000)
struct WBP_UI_Widget_EscapeCounter_C_UpdateEscapeWidgetText final
{
public:
	int32                                         InPlayersInVolume;                                 // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         InTotalPlayers;                                    // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0008(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0048(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0088(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0098(0x0018)()
};
DUMPER7_ASSERTS_WBP_UI_Widget_EscapeCounter_C_UpdateEscapeWidgetText;

}

