#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Loadout_RenamePopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Loadout_RenamePopup.WBP_Loadout_RenamePopup_C
// 0x0020 (0x02B0 - 0x0290)
class UWBP_Loadout_RenamePopup_C final : public USBZWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_TextEntry_Button_C*                Textbox_LoadoutName;                               // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UI_Preplanning_MainMenu_LoadoutButton_C* Owner_LoadoutButton;                         // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         MaxStrLen;                                         // 0x02A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Loadout_RenamePopup(int32 EntryPoint);
	void OnInitialized();
	void UpdateName(const class FText& Text);
	void Construct();
	void ShowCurrentName(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Loadout_RenamePopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Loadout_RenamePopup_C")
	}
	static class UWBP_Loadout_RenamePopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Loadout_RenamePopup_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Loadout_RenamePopup_C;

}

