#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_PlayerStatusWidget

#include "Basic.hpp"

#include "WBP_UI_Widget_PlayerStatusWidget_classes.hpp"
#include "WBP_UI_Widget_PlayerStatusWidget_parameters.hpp"


namespace SDK
{

// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.ExecuteUbergraph_WBP_UI_Widget_PlayerStatusWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Widget_PlayerStatusWidget_C::ExecuteUbergraph_WBP_UI_Widget_PlayerStatusWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "ExecuteUbergraph_WBP_UI_Widget_PlayerStatusWidget");

	Params::WBP_UI_Widget_PlayerStatusWidget_C_ExecuteUbergraph_WBP_UI_Widget_PlayerStatusWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.OnHeisterIconChangedEvent
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPaperSprite*                     InNewHeisterIcon                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Widget_PlayerStatusWidget_C::OnHeisterIconChangedEvent(class UPaperSprite* InNewHeisterIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "OnHeisterIconChangedEvent");

	Params::WBP_UI_Widget_PlayerStatusWidget_C_OnHeisterIconChangedEvent Parms{};

	Parms.InNewHeisterIcon = InNewHeisterIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.OnStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPD3DefeatState                         Old                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPD3DefeatState                         New                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Widget_PlayerStatusWidget_C::OnStateChanged(EPD3DefeatState Old, EPD3DefeatState New)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "OnStateChanged");

	Params::WBP_UI_Widget_PlayerStatusWidget_C_OnStateChanged Parms{};

	Parms.Old = Old;
	Parms.New = New;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Widget_PlayerStatusWidget_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.On Damage
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZDamageEvent&           DamageEventData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_UI_Widget_PlayerStatusWidget_C::On_Damage(const struct FSBZDamageEvent& DamageEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "On Damage");

	Params::WBP_UI_Widget_PlayerStatusWidget_C_On_Damage Parms{};

	Parms.DamageEventData = std::move(DamageEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Widget_PlayerStatusWidget_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Widget_PlayerStatusWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_Widget_PlayerStatusWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "PreConstruct");

	Params::WBP_UI_Widget_PlayerStatusWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Widget_PlayerStatusWidget.WBP_UI_Widget_PlayerStatusWidget_C.SetEOSProdUID
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UI_Widget_PlayerStatusWidget_C::SetEOSProdUID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Widget_PlayerStatusWidget_C", "SetEOSProdUID");

	UObject::ProcessEvent(Func, nullptr);
}

}

