#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HackingZoneControllerDisabled

#include "Basic.hpp"

#include "WBP_HackingZoneControllerDisabled_classes.hpp"
#include "WBP_HackingZoneControllerDisabled_parameters.hpp"


namespace SDK
{

// Function WBP_HackingZoneControllerDisabled.WBP_HackingZoneControllerDisabled_C.ExecuteUbergraph_WBP_HackingZoneControllerDisabled
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HackingZoneControllerDisabled_C::ExecuteUbergraph_WBP_HackingZoneControllerDisabled(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HackingZoneControllerDisabled_C", "ExecuteUbergraph_WBP_HackingZoneControllerDisabled");

	Params::WBP_HackingZoneControllerDisabled_C_ExecuteUbergraph_WBP_HackingZoneControllerDisabled Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HackingZoneControllerDisabled.WBP_HackingZoneControllerDisabled_C.setText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_HackingZoneControllerDisabled_C::setText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HackingZoneControllerDisabled_C", "setText");

	Params::WBP_HackingZoneControllerDisabled_C_setText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}

}

