#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XeFGBlueprint

#include "Basic.hpp"

#include "XeFGBlueprint_structs.hpp"


namespace SDK::Params
{

// Function XeFGBlueprint.XeFGBlueprintLibrary.GetSupportedXeFGModes
// 0x0010 (0x0010 - 0x0000)
struct XeFGBlueprintLibrary_GetSupportedXeFGModes final
{
public:
	TArray<EXeFGMode>                             ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_XeFGBlueprintLibrary_GetSupportedXeFGModes;

// Function XeFGBlueprint.XeFGBlueprintLibrary.GetXeFGMode
// 0x0001 (0x0001 - 0x0000)
struct XeFGBlueprintLibrary_GetXeFGMode final
{
public:
	EXeFGMode                                     ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_XeFGBlueprintLibrary_GetXeFGMode;

// Function XeFGBlueprint.XeFGBlueprintLibrary.IfRelaunchRequiredByXeFG
// 0x0001 (0x0001 - 0x0000)
struct XeFGBlueprintLibrary_IfRelaunchRequiredByXeFG final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_XeFGBlueprintLibrary_IfRelaunchRequiredByXeFG;

// Function XeFGBlueprint.XeFGBlueprintLibrary.IsXeFGSupported
// 0x0001 (0x0001 - 0x0000)
struct XeFGBlueprintLibrary_IsXeFGSupported final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_XeFGBlueprintLibrary_IsXeFGSupported;

// Function XeFGBlueprint.XeFGBlueprintLibrary.SetXeFGMode
// 0x0001 (0x0001 - 0x0000)
struct XeFGBlueprintLibrary_SetXeFGMode final
{
public:
	EXeFGMode                                     Mode;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_XeFGBlueprintLibrary_SetXeFGMode;

}

